# numpy Library

In [1]:
import numpy as np

In [2]:
np.eye?

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

In [7]:
x = np.array([2,3,5,1]) # 1D array
x2d = np.array([[1,2,3],[4,5,6]])
x3d = np.array([[[1,3],[4,2]],[[2,1],[3,4]]])
print(x)
print(x2d)

[2 3 5 1]
[[1 2 3]
 [4 5 6]]


In [8]:
# sequential matrix, np.arange() and np.linspace()
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [11]:
np.arange(0, 10, .2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [10]:
np.arange(0, 10, .2).size

50

In [12]:
np.arange(0, 10, .2).reshape(5,10)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [17]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [21]:
np.linspace(0, 15, 4).reshape(2,2)

array([[ 0.,  5.],
       [10., 15.]])

# randomized matrix with np.random
# np.random.rand()

In [25]:
print(np.random.rand(2,2)) #0 to 1
# np.random.randn() #normal distribution

print(np.random.randn(3,3))
#np.random randit()

print(np.random.randint(-10,10,(3,3))) #random int from -10 to 10
#np.random uniform()

print(np.random.uniform(0,2,(3,3))) #random uniform from 0 to 2
#np.random permutation()

print(np.random.permutation([1,2,3,4,5,6,7,8,9,10])) #random permutation

[[0.54787062 0.62310162]
 [0.69367908 0.05886247]]
[[ 1.06298042 -0.19847682  0.27087647]
 [-0.29478752 -0.37363785 -1.07779149]
 [-0.20064495 -0.99139482 -0.15182837]]
[[  5   7  -3]
 [ -8 -10   6]
 [  0   0   3]]
[[1.00165793 0.51844836 0.8220251 ]
 [1.10478314 0.3646805  1.51728809]
 [0.99789647 1.74307468 0.34577979]]
[ 9  2  8  4  6  1  7  3 10  5]


# operations




In [27]:
a = np.random.randint(-10,10,(3,3))
b = np.random.randint(-10,10,(3,3))
print(a)
print(b)


[[-7  8 -1]
 [ 4 -5 -9]
 [-9  5  8]]
[[ 9  5 -3]
 [ 0 -6  4]
 [ 7 -2  2]]


In [28]:
a **2

array([[49, 64,  1],
       [16, 25, 81],
       [81, 25, 64]])

In [29]:
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a@b) #matrix multiplication

[[  2  13  -4]
 [  4 -11  -5]
 [ -2   3  10]]
[[-16   3   2]
 [  4   1 -13]
 [-16   7   6]]
[[-0.77777778  1.6         0.33333333]
 [        inf  0.83333333 -2.25      ]
 [-1.28571429 -2.5         4.        ]]
[[-63  40   3]
 [  0  30 -36]
 [-63 -10  16]]
[[-70 -81  51]
 [-27  68 -50]
 [-25 -91  63]]


C:\Users\win-10\AppData\Local\Temp\ipykernel_6368\1012109709.py:3: RuntimeWarning: divide by zero encountered in divide
  print(a/b)


In [30]:

np.matmul(a,b) #or np.dot(a,b) or a @b

array([[-70, -81,  51],
       [-27,  68, -50],
       [-25, -91,  63]])